// Menu data for the drawer navigation
export const MENU_ITEMS = [
  {
    id: "zodiac-info",
    titleEn: "Zodiac Details & Astrology Information",
    titleNe: "राशी विवरण र ज्योतिष जानकारी",
    route: "/astrology/zodiac-info",
    icon: "🌟",
  },
  {
    id: "name-category",
    titleEn: "Name First Letter Category Table",
    titleNe: "नामको पहिलो अक्षरबाट वर्ग हेर्ने तालिका",
    route: "/astrology/name-category",
    icon: "📝",
  },
  {
    id: "hora-knowledge",
    titleEn: "Hora Knowledge Table",
    titleNe: "होड़ा ज्ञान तालिका",
    route: "/astrology/hora-knowledge",
    icon: "📊",
  },
  {
    id: "festivals-mantras",
    titleEn: "Annual Festivals & Mantras Details",
    titleNe: "वार्षिक चाडपर्व एवं मन्त्रहरुको विवरण",
    route: "/astrology/festivals-mantras",
    icon: "🎉",
  },
];

// Name category mapping data
export const NAME_CATEGORY_DATA = [
  { letters: "अ, इ, उ, ए", category: "गरुड (बैर-सर्प)" },
  { letters: "क, ख, ग, घ, ङ", category: "बिरालो (बैर-मुता)" },
  { letters: "च, छ, ज, स, ञ", category: "सिंह (बैर-मृग)" },
  { letters: "ट, उ, ड, द, ण", category: "कुकुर (वैर-न्याउरी)" },
  { letters: "त, ब, द, घ, न", category: "सर्प (बैर-गरुड)" },
  { letters: "प, फ, ब, भ, म", category: "मुसा (वैर-विरालो)" },
  { letters: "प, र, ल, व", category: "मूग (वैर-सिंह)" },
  { letters: "श, व, स, ह", category: "न्याउरी (बैर-कुकुर)" },
];

// Hora knowledge table data
export const HORA_KNOWLEDGE_DATA = [
  {
    letters: "चू,चे,चो,ला",
    nakshatra: "अश्विनी",
    rashi: "मेष",
    swami: "मंगल",
    kshan: "क्षत्रिय",
    paksha: "शुक्ल",
    year: "विक्रम",
    rashi2: "मेष",
    animal: "बाघ",
    gan: "देवता",
    nadi: "आदि",
    adra: "घोड़ा",
  },
  {
    letters: "ली,लु,ले,लो",
    nakshatra: "भरणी",
    rashi: "मेष",
    swami: "मंगल",
    kshan: "क्षत्रिय",
    paksha: "कृष्ण",
    year: "शक",
    rashi2: "सिंह",
    animal: "सिंह",
    gan: "मनुष्य",
    nadi: "मध्य",
    adra: "प्रेत",
  },
  {
    letters: "अ,इ,उ,ए",
    nakshatra: "कृत्तिका",
    rashi: "वृष",
    swami: "शुक्र",
    kshan: "वैश्य",
    paksha: "शुक्ल",
    year: "विक्रम",
    rashi2: "कन्या",
    animal: "कुत्ता",
    gan: "राक्षस",
    nadi: "अन्त्य",
    adra: "अग्नि",
  },
  {
    letters: "ओ,वा,वी,वु",
    nakshatra: "रोहिणी",
    rashi: "वृष",
    swami: "शुक्र",
    kshan: "शुद्र",
    paksha: "कृष्ण",
    year: "शक",
    rashi2: "तुला",
    animal: "सर्प",
    gan: "मनुष्य",
    nadi: "आदि",
    adra: "चन्द्र",
  },
  {
    letters: "वे,वो,का,की",
    nakshatra: "मृगशिरा",
    rashi: "मिथुन",
    swami: "बुध",
    kshan: "वैश्य",
    paksha: "शुक्ल",
    year: "विक्रम",
    rashi2: "वृश्चिक",
    animal: "सर्प",
    gan: "देवता",
    nadi: "मध्य",
    adra: "मंगल",
  },
];

// Festival data structure (sample data)
export const FESTIVALS_DATA = [
  {
    id: 1,
    nameNe: "दशैं",
    nameEn: "Dashain",
    date: "आश्विन शुक्ल प्रतिपदा देखि दशमी",
    description: "नेपालको सबैभन्दा ठूलो चाड। दुर्गा माताको पूजा गरिन्छ।",
    mantras: ["ॐ दुं दुर्गायै नमः", "सर्वमंगल मांगल्ये शिवे सर्वार्थ साधिके"],
    significance: "बुराईमाथि असलको विजय",
    rituals: ["कलश स्थापना", "नवरात्रि व्रत", "विजया दशमी टीका"],
  },
  {
    id: 2,
    nameNe: "तिहार",
    nameEn: "Tihar",
    date: "कार्तिक कृष्ण त्रयोदशी देखि शुक्ल द्वितीया",
    description: "पाँच दिने चाड। लक्ष्मी पूजा र दीपावली मनाइन्छ।",
    mantras: [
      "ॐ श्रीं लक्ष्म्यै नमः",
      "या देवी सर्वभूतेषु लक्ष्मी रूपेण संस्थिता",
    ],
    significance: "धन र समृद्धिको देवी लक्ष्मीको पूजा",
    rituals: ["काग पूजा", "कुकुर पूजा", "गाई पूजा", "गोरु पूजा", "भाई टीका"],
  },
  {
    id: 3,
    nameNe: "होली",
    nameEn: "Holi",
    date: "फागुन पूर्णिमा",
    description: "रंगहरूको चाड। होलिका दहन र रंग खेल्ने परम्परा।",
    mantras: ["ॐ होलिकायै नमः", "राधे कृष्ण राधे कृष्ण कृष्ण कृष्ण राधे राधे"],
    significance: "बसन्त ऋतुको स्वागत र बुराईको अन्त्य",
    rituals: ["होलिका दहन", "रंग खेल्ने", "मिठाई बाँड्ने"],
  },
];
