// Menu data for the drawer navigation
export const MENU_ITEMS = [
  {
    id: "zodiac-info",
    titleEn: "Zodiac Details & Astrology Information",
    titleNe: "राशी विवरण र ज्योतिष जानकारी",
    route: "/astrology/zodiac-info",
    icon: "🌟",
  },
  {
    id: "name-category",
    titleEn: "Name First Letter Category Table",
    titleNe: "नामको पहिलो अक्षरबाट वर्ग हेर्ने तालिका",
    route: "/astrology/name-category",
    icon: "📝",
  },
  {
    id: "name-horoscope",
    route: "/astrology/name-horoscope",
    icon: "☀️",
    titleEn: "Name Horoscope Table",
    titleNe: "नामको पहिलो अक्षरबाट राशी हेर्ने तालिका",
  },

  {
    id: "hora-knowledge",
    titleEn: "Hora Knowledge Table",
    titleNe: "होड़ा ज्ञान तालिका",
    route: "/astrology/hora-knowledge",
    icon: "📊",
  },
  {
    id: "festivals-mantras",
    titleEn: "Annual Festivals & Mantras Details",
    titleNe: "वार्षिक चाडपर्व एवं मन्त्रहरुको विवरण",
    route: "/astrology/festivals-mantras",
    icon: "🎉",
  },
];

// Name category mapping data
export const NAME_CATEGORY_DATA = [
  { letters: "अ, इ, उ, ए", category: "गरुड (वैर-सर्प)" },
  { letters: "क, ख, ग, घ, ङ", category: "बिरालो (वैर-मुसा)" },
  { letters: "च, छ, ज, स, ञ", category: "सिंह (वैर-मृग)" },
  { letters: "ट, उ, ड, द, ण", category: "कुकुर (वैर-न्याउरी)" },
  { letters: "त, ब, द, घ, न", category: "सर्प (वैर-गरुड)" },
  { letters: "प, फ, ब, भ, म", category: "मुसा (वैर-विरालो)" },
  { letters: "प, र, ल, व", category: "मूग (वैर-सिंह)" },
  { letters: "श, व, स, ह", category: "न्याउरी (वैर-कुकुर)" },
];

export const NAME_HOROSCOPE_DATA = [
  { letters: "चु, चे, चो, ला, लि, लु, ले, लो, अ", horoscope: "मेष" },
  { letters: "इ, उ, ए, ओ, वा, वि, वु, वे, वो", horoscope: "वृष" },
  { letters: "का, कि, कु, घ, ङ, छ, के, को, हा", horoscope: "मिथुन" },
  { letters: "हि, हु, हे, हो, डा, डि, डु, डे, डो", horoscope: "कर्कट" },
  { letters: "मा, मि, मु, मे, मो, टा, टि, टु, टे", horoscope: "सिंह" },
  { letters: "टो, पा, पि, पु, ष, ण, ठ, पे, पो", horoscope: "कन्या" },
  { letters: "रा, रि, रु, रे, रो, ता, ति, तु, ते", horoscope: "तुला" },
  { letters: "तो, ना, नि, नु, ने, नो, या, यि, यु", horoscope: "वृश्चिक" },
  { letters: "ये, यो, भा, भि, भु, धा, फा, ढा, भे", horoscope: "धनु" },
  {
    letters: "भो, जा, जि, जु, जे, जो, ख, खि, खु, खे, खो, गा, गि",
    horoscope: "मकर",
  },
  { letters: "गु, गे, गो, सा, सि, सु, से, सो, दा", horoscope: "कुम्भ" },
  { letters: "दि, दु, थ, झ, ञ, दे, दो, चा, चि", horoscope: "मीन" },
];
// Hora knowledge table data
export const HORA_KNOWLEDGE_DATA = [
  {
    letters: "चू,चे,चो,ला",
    nakshatra: "अश्विनी",
    rashi: "मेष",
    swami: "मंगल",
    kshan: "क्षत्रिय",
    paksha: "शुक्ल",
    year: "विक्रम",
    rashi2: "मेष",
    animal: "बाघ",
    gan: "देवता",
    nadi: "आदि",
    adra: "घोड़ा",
  },
  {
    letters: "ली,लु,ले,लो",
    nakshatra: "भरणी",
    rashi: "मेष",
    swami: "मंगल",
    kshan: "क्षत्रिय",
    paksha: "कृष्ण",
    year: "शक",
    rashi2: "सिंह",
    animal: "सिंह",
    gan: "मनुष्य",
    nadi: "मध्य",
    adra: "प्रेत",
  },
  {
    letters: "अ,इ,उ,ए",
    nakshatra: "कृत्तिका",
    rashi: "वृष",
    swami: "शुक्र",
    kshan: "वैश्य",
    paksha: "शुक्ल",
    year: "विक्रम",
    rashi2: "कन्या",
    animal: "कुत्ता",
    gan: "राक्षस",
    nadi: "अन्त्य",
    adra: "अग्नि",
  },
  {
    letters: "ओ,वा,वी,वु",
    nakshatra: "रोहिणी",
    rashi: "वृष",
    swami: "शुक्र",
    kshan: "शुद्र",
    paksha: "कृष्ण",
    year: "शक",
    rashi2: "तुला",
    animal: "सर्प",
    gan: "मनुष्य",
    nadi: "आदि",
    adra: "चन्द्र",
  },
  {
    letters: "वे,वो,का,की",
    nakshatra: "मृगशिरा",
    rashi: "मिथुन",
    swami: "बुध",
    kshan: "वैश्य",
    paksha: "शुक्ल",
    year: "विक्रम",
    rashi2: "वृश्चिक",
    animal: "सर्प",
    gan: "देवता",
    nadi: "मध्य",
    adra: "मंगल",
  },
];

// Festival data structure (sample data)
export const FESTIVALS_DATA = [
  {
    id: 1,
    nameNe: "दशैं",
    nameEn: "Dashain",
    date: "आश्विन शुक्ल प्रतिपदा देखि दशमी",
    description: "नेपालको सबैभन्दा ठूलो चाड। दुर्गा माताको पूजा गरिन्छ।",
    mantras: ["ॐ दुं दुर्गायै नमः", "सर्वमंगल मांगल्ये शिवे सर्वार्थ साधिके"],
    significance: "असत्य माथि सत्यको विजय",
    rituals: ["कलश स्थापना", "नवरात्रि व्रत", "विजया दशमी टीका"],
  },
  {
    id: 2,
    nameNe: "तिहार",
    nameEn: "Tihar",
    date: "कार्तिक कृष्ण त्रयोदशी देखि शुक्ल द्वितीया",
    description: "पाँच दिने चाड। लक्ष्मी पूजा र दीपावली मनाइन्छ।",
    mantras: [
      "ॐ श्रीं लक्ष्म्यै नमः",
      "या देवी सर्वभूतेषु लक्ष्मी रूपेण संस्थिता",
    ],
    significance: "धन र समृद्धिको देवी लक्ष्मीको पूजा साथै भाई टीका",
    rituals: ["काग पूजा", "कुकुर पूजा", "गाई पूजा", "गोरु पूजा", "भाई टीका"],
  },
  {
    id: 3,
    nameNe: "होली",
    nameEn: "Holi",
    date: "फागुन पूर्णिमा",
    description: "रंगहरूको चाड। होलिका दहन र रंग खेल्ने परम्परा।",
    mantras: ["ॐ होलिकायै नमः", "राधे कृष्ण राधे कृष्ण कृष्ण कृष्ण राधे राधे"],
    significance: "बसन्त ऋतुको स्वागत र बुराईको अन्त्य",
    rituals: ["रंग खेल्ने", "मिठाई बाँड्ने"],
  },
];

// constants/menuData.ts

export const ATHAVAKHADA_DATA = [
  {
    nakshatra: "अश्विनी",
    naamakshar: "चु, चे, चो, ला",
    rashi: "मेष",
    swami: "भौम (मंगल)",
    varna: "क्षेत्री",
    vashya: "चतुष्पद",
    yoni: "अश्व",
    vairYoni: "महिष",
    gan: "देव",
    nadi: "आद्य",
    aasan: "अश्व",
  },
  {
    nakshatra: "भरणी",
    naamakshar: "ली, लू, ले, लो",
    rashi: "मेष",
    swami: "भौम",
    varna: "क्षत्री",
    vashya: "चतुष्पद",
    yoni: "गज",
    vairYoni: "सिंह",
    gan: "नर",
    nadi: "मध्य",
    aasan: "प्रेत",
  },
  {
    nakshatra: "कृत्तिका",
    naamakshar: "अ, ई, ऊ, ए",
    rashi: "मेष:१ / वृष:३",
    swami: "भौम१ / शुक्र३",
    varna: "क्षेत्री१ / वैश्य३",
    vashya: "चतुष्पद",
    yoni: "अज",
    vairYoni: "वानर",
    gan: "राक्षस",
    nadi: "अन्त्य",
    aasan: "अग्निकुण्ड",
  },
  {
    nakshatra: "रोहिणी",
    naamakshar: "ओ, वा, वी, वू",
    rashi: "वृष",
    swami: "शुक्र",
    varna: "वैश्य",
    vashya: "चतुष्पद",
    yoni: "सर्प",
    vairYoni: "नकुल",
    gan: "नर",
    nadi: "अन्त्य",
    aasan: "गौ",
  },
  {
    nakshatra: "मृगशिरा",
    naamakshar: "वे, वो, का, की",
    rashi: "वृष:२ / मिथुन:२",
    swami: "शुक्र:२ / बुध:२",
    varna: "वैश्य:२ / शुद्र:२",
    vashya: "चतुष्पद:२ / द्विपद:२",
    yoni: "सर्प",
    vairYoni: "नकुल",
    gan: "देव",
    nadi: "मध्य",
    aasan: "मृग",
  },
  {
    nakshatra: "आर्द्रा",
    naamakshar: "कु, घ, ङ, छ",
    rashi: "मिथुन",
    swami: "बुध",
    varna: "शुद्र",
    vashya: "द्विपद",
    yoni: "श्वान",
    vairYoni: "मृग",
    gan: "नर",
    nadi: "आद्य",
    aasan: "सर्प",
  },
  {
    nakshatra: "पुनर्वसु",
    naamakshar: "के, को, हा, ही",
    rashi: "मिथुन:३ / कर्कट:१",
    swami: "बुध:३ / चन्द्र:१",
    varna: "शुद्र:३ / विप्र:१",
    vashya: "द्विपद:३ / जलचर:१",
    yoni: "मार्जर",
    vairYoni: "मुषक",
    gan: "देव",
    nadi: "आद्य",
    aasan: "कमल",
  },
  {
    nakshatra: "तिष्य",
    naamakshar: "हू, हे, हो, डा",
    rashi: "कर्कट",
    swami: "चन्द्र",
    varna: "विप्र",
    vashya: "जलचर",
    yoni: "अज",
    vairYoni: "वानर",
    gan: "देव",
    nadi: "मध्य",
    aasan: "कलश",
  },
  {
    nakshatra: "अश्लेषा",
    naamakshar: "डी, डू, डे, डो",
    rashi: "कर्कट",
    swami: "चन्द्र",
    varna: "विप्र",
    vashya: "जलचर",
    yoni: "मार्जर",
    vairYoni: "मुषक",
    gan: "राक्षस",
    nadi: "अन्त्य",
    aasan: "काक",
  },
  {
    nakshatra: "मघा",
    naamakshar: "मा, मी, मू, मे",
    rashi: "सिंह",
    swami: "सूर्य",
    varna: "क्षेत्री",
    vashya: "चतुष्पद",
    yoni: "मुषक",
    vairYoni: "मार्जर",
    gan: "राक्षस",
    nadi: "अन्त्य",
    aasan: "महिष",
  },
  {
    nakshatra: "पूर्वाफाल्गुनी",
    naamakshar: "मो, टा, टी, टू",
    rashi: "सिंह",
    swami: "सूर्य",
    varna: "क्षत्री",
    vashya: "चतुष्पद",
    yoni: "मुषक",
    vairYoni: "मार्जार",
    gan: "नर",
    nadi: "मध्य",
    aasan: "शिला",
  },
  {
    nakshatra: "उत्तरफल्गुनी",
    naamakshar: "ते, तो, पा, पी",
    rashi: "सिंह:१ / कन्या:३",
    swami: "सूर्य:१ / बुध:३",
    varna: "क्षेत्री:१ / वैश्य:३",
    vashya: "चतुष्पद:१ / द्विपद:३",
    yoni: "गौ",
    vairYoni: "व्याघ्र",
    gan: "नर",
    nadi: "आद्य",
    aasan: "शिला",
  },
  {
    nakshatra: "हस्ता",
    naamakshar: "पू, ष, ण, ठ",
    rashi: "कन्या",
    swami: "बुध",
    varna: "वैश्य",
    vashya: "द्विपद",
    yoni: "महिष",
    vairYoni: "अश्व",
    gan: "देव",
    nadi: "आद्य",
    aasan: "गज",
  },
  {
    nakshatra: "चित्रा",
    naamakshar: "पे, पो, रा, री",
    rashi: "कन्या:२ / तुला:२",
    swami: "बुध:२ / शुक्र:२",
    varna: "वैश्य:२ / शुद्र:२",
    vashya: "द्विपद",
    yoni: "व्याघ्र",
    vairYoni: "गौ",
    gan: "राक्षस",
    nadi: "मध्य",
    aasan: "मयूर",
  },
  {
    nakshatra: "स्वाति",
    naamakshar: "रू, रे, रो, ता",
    rashi: "तुला",
    swami: "शुक्र",
    varna: "शुद्र",
    vashya: "द्विपद",
    yoni: "महिष",
    vairYoni: "अश्व",
    gan: "देव",
    nadi: "अन्त्य",
    aasan: "दोल",
  },
  {
    nakshatra: "विशाखा",
    naamakshar: "ती, तू, ते, तो",
    rashi: "तुला:३ / वृश्चिक:१",
    swami: "शुक्र:३ / मंगल:१",
    varna: "शुद्र:३ / विप्र:१",
    vashya: "द्विपद:३ / कीट:१",
    yoni: "व्याघ्र",
    vairYoni: "गौ",
    gan: "राक्षस",
    nadi: "अन्त्य",
    aasan: "अज",
  },
  {
    nakshatra: "अनुराधा",
    naamakshar: "ना, नी, नू, ने",
    rashi: "वृश्चिक",
    swami: "मंगल",
    varna: "विप्र",
    vashya: "कीट",
    yoni: "मृग",
    vairYoni: "श्वान",
    gan: "देव",
    nadi: "मध्य",
    aasan: "हंस",
  },
  {
    nakshatra: "ज्येष्ठा",
    naamakshar: "नो, या, यी, यू",
    rashi: "वृश्चिक",
    swami: "मंगल",
    varna: "विप्र",
    vashya: "कीट",
    yoni: "मृग",
    vairYoni: "श्वान",
    gan: "राक्षस",
    nadi: "आद्य",
    aasan: "कच्छप",
  },
  {
    nakshatra: "मूल",
    naamakshar: "ये, यो, भा, भी",
    rashi: "धनु",
    swami: "बृहस्पति",
    varna: "क्षत्री",
    vashya: "मनुष्य",
    yoni: "श्वान",
    vairYoni: "मृग",
    gan: "राक्षस",
    nadi: "आद्य",
    aasan: "मूल",
  },
  {
    nakshatra: "पूर्वाषाढा",
    naamakshar: "भू, ध, फा, ढा",
    rashi: "धनु",
    swami: "बृहस्पति",
    varna: "क्षत्री",
    vashya: "मनुष्य:१ / चतुष्पद:३",
    yoni: "वानर",
    vairYoni: "अज",
    gan: "नर",
    nadi: "मध्य",
    aasan: "शयन",
  },
  {
    nakshatra: "उत्तराषाढा",
    naamakshar: "भे, भो, जा, जी",
    rashi: "धनु:१ / मकर:३",
    swami: "बृहस्पति:१ / शनि:३",
    varna: "क्षत्री:१ / वैश्य:३",
    vashya: "मनुष्य:१ / चतुष्पद:३",
    yoni: "नकुल",
    vairYoni: "सर्प",
    gan: "नर",
    nadi: "अन्त्य",
    aasan: "शयन",
  },
  {
    nakshatra: "अभिजित",
    naamakshar: "जू, जे, जो, ख",
    rashi: "मकर",
    swami: "शनि",
    varna: "वैश्य",
    vashya: "चतुष्पद",
    yoni: "नकुल / अज",
    vairYoni: "अज / गज",
    gan: "नर / देव",
    nadi: "अन्त्य",
    aasan: "शयन",
  },
  {
    nakshatra: "श्रवण",
    naamakshar: "खा, खी, खू, खे",
    rashi: "मकर",
    swami: "शनि",
    varna: "वैश्य",
    vashya: "श्रवण:१ / चतुष्पद:२ / द्विपद",
    yoni: "वानर",
    vairYoni: "अज",
    gan: "देव",
    nadi: "अन्त्य",
    aasan: "नर",
  },
  {
    nakshatra: "धनिष्ठा",
    naamakshar: "गा, गी, गु, गे",
    rashi: "मकर:२ / कुम्भ:२",
    swami: "शनि",
    varna: "वैश्य:२ / शुद्र:२",
    vashya: "चतुष्पद:२ / द्विपद:२",
    yoni: "सिंह",
    vairYoni: "गज",
    gan: "राक्षस",
    nadi: "मध्य",
    aasan: "आढक",
  },
  {
    nakshatra: "शतभिषा",
    naamakshar: "गो, सा, सी, सु",
    rashi: "कुम्भ",
    swami: "शनि",
    varna: "शुद्र",
    vashya: "अश्व",
    yoni: "महिष",
    vairYoni: "महिष",
    gan: "राक्षस",
    nadi: "आद्य",
    aasan: "वृष",
  },
  {
    nakshatra: "पूर्वाभाद्रपदा",
    naamakshar: "से, सो, दा, दी",
    rashi: "कुम्भ:३ / मीन:१",
    swami: "शनि:३ / बृहस्पति:१",
    varna: "शुद्र:३ / विप्र:१",
    vashya: "द्विपद:३ / जलचर:१",
    yoni: "सिंह",
    vairYoni: "गज",
    gan: "नर",
    nadi: "आद्य",
    aasan: "भद्रपिठ",
  },
  {
    nakshatra: "उत्तराभाद्रपदा",
    naamakshar: "दू, थ, झ, ञ",
    rashi: "मीन",
    swami: "बृहस्पति",
    varna: "विप्र",
    vashya: "जलचर",
    yoni: "गौ",
    vairYoni: "व्याघ्र",
    gan: "नर",
    nadi: "मध्य",
    aasan: "भद्रपिठ",
  },
  {
    nakshatra: "रेवती",
    naamakshar: "दे, दो, चा, ची",
    rashi: "मीन",
    swami: "बृहस्पति",
    varna: "विप्र",
    vashya: "जलचर",
    yoni: "गज",
    vairYoni: "सिंह",
    gan: "देव",
    nadi: "अन्त्य",
    aasan: "चक्र",
  },
];
