import { ZodiacInfo } from '@/types/astrology';

export const ZODIAC_DATA: Record<string, ZodiacInfo> = {
  aries: {
    nameEn: 'Aries',
    nameNe: 'मेष',
    symbol: '♈',
    element: 'Fire',
    elementNe: 'अग्नि',
    gana: 'Deva',
    ganaNe: 'देव गण',
    deity: 'Mars',
    deityNe: 'मंगल',
    planet: 'Mars',
    planetNe: 'मंगल',
    luckyColor: 'Red',
    luckyColorNe: 'रातो',
    gemstone: 'Red Coral',
    gemstoneNe: 'मूंगा',
    luckyNumbers: [1, 8, 17],
    luckyDays: ['Tuesday', 'Saturday'],
    luckyDaysNe: ['मंगलबार', 'शनिबार'],
    traits: ['Energetic', 'Leadership', 'Courageous', 'Independent'],
    traitsNe: ['ऊर्जावान', 'नेतृत्व', 'साहसी', 'स्वतन्त्र'],
    compatibility: ['Leo', 'Sagittarius', 'Gemini'],
    compatibilityNe: ['सिंह', 'धनु', 'मिथुन'],
    direction: 'East',
    directionNe: 'पूर्व',
    metal: 'Iron',
    metalNe: 'फलाम',
    flower: 'Red Rose',
    flowerNe: 'रातो गुलाब'
  },
  taurus: {
    nameEn: 'Taurus',
    nameNe: 'वृषभ',
    symbol: '♉',
    element: 'Earth',
    elementNe: 'पृथ्वी',
    gana: 'Manushya',
    ganaNe: 'मनुष्य गण',
    deity: 'Venus',
    deityNe: 'शुक्र',
    planet: 'Venus',
    planetNe: 'शुक्र',
    luckyColor: 'White, Pink',
    luckyColorNe: 'सेतो, गुलाबी',
    gemstone: 'Diamond',
    gemstoneNe: 'हीरा',
    luckyNumbers: [2, 6, 9],
    luckyDays: ['Friday', 'Monday'],
    luckyDaysNe: ['शुक्रबार', 'सोमबार'],
    traits: ['Reliable', 'Patient', 'Practical', 'Devoted'],
    traitsNe: ['भरपर्दो', 'धैर्यवान', 'व्यावहारिक', 'समर्पित'],
    compatibility: ['Virgo', 'Capricorn', 'Cancer'],
    compatibilityNe: ['कन्या', 'मकर', 'कर्कट'],
    direction: 'South',
    directionNe: 'दक्षिण',
    metal: 'Copper',
    metalNe: 'तामा',
    flower: 'White Lotus',
    flowerNe: 'सेतो कमल'
  },
  gemini: {
    nameEn: 'Gemini',
    nameNe: 'मिथुन',
    symbol: '♊',
    element: 'Air',
    elementNe: 'वायु',
    gana: 'Manushya',
    ganaNe: 'मनुष्य गण',
    deity: 'Mercury',
    deityNe: 'बुध',
    planet: 'Mercury',
    planetNe: 'बुध',
    luckyColor: 'Green, Yellow',
    luckyColorNe: 'हरियो, पहेंलो',
    gemstone: 'Emerald',
    gemstoneNe: 'पन्ना',
    luckyNumbers: [5, 14, 23],
    luckyDays: ['Wednesday', 'Friday'],
    luckyDaysNe: ['बुधबार', 'शुक्रबार'],
    traits: ['Adaptable', 'Outgoing', 'Intelligent', 'Curious'],
    traitsNe: ['अनुकूलनशील', 'मिलनसार', 'बुद्धिमान', 'जिज्ञासु'],
    compatibility: ['Libra', 'Aquarius', 'Aries'],
    compatibilityNe: ['तुला', 'कुम्भ', 'मेष'],
    direction: 'North',
    directionNe: 'उत्तर',
    metal: 'Bronze',
    metalNe: 'कांस्य',
    flower: 'Lily',
    flowerNe: 'लिली'
  },
  cancer: {
    nameEn: 'Cancer',
    nameNe: 'कर्कट',
    symbol: '♋',
    element: 'Water',
    elementNe: 'जल',
    gana: 'Deva',
    ganaNe: 'देव गण',
    deity: 'Moon',
    deityNe: 'चन्द्र',
    planet: 'Moon',
    planetNe: 'चन्द्र',
    luckyColor: 'White, Silver',
    luckyColorNe: 'सेतो, चाँदी',
    gemstone: 'Pearl',
    gemstoneNe: 'मोती',
    luckyNumbers: [2, 7, 11],
    luckyDays: ['Monday', 'Thursday'],
    luckyDaysNe: ['सोमबार', 'बिहीबार'],
    traits: ['Emotional', 'Loving', 'Protective', 'Intuitive'],
    traitsNe: ['भावनात्मक', 'प्रेमी', 'सुरक्षात्मक', 'अन्तर्ज्ञानी'],
    compatibility: ['Scorpio', 'Pisces', 'Taurus'],
    compatibilityNe: ['वृश्चिक', 'मीन', 'वृषभ'],
    direction: 'Northwest',
    directionNe: 'उत्तर-पश्चिम',
    metal: 'Silver',
    metalNe: 'चाँदी',
    flower: 'White Rose',
    flowerNe: 'सेतो गुलाब'
  },
  leo: {
    nameEn: 'Leo',
    nameNe: 'सिंह',
    symbol: '♌',
    element: 'Fire',
    elementNe: 'अग्नि',
    gana: 'Rakshasa',
    ganaNe: 'राक्षस गण',
    deity: 'Sun',
    deityNe: 'सूर्य',
    planet: 'Sun',
    planetNe: 'सूर्य',
    luckyColor: 'Gold, Orange',
    luckyColorNe: 'सुनौलो, सुन्तला',
    gemstone: 'Ruby',
    gemstoneNe: 'माणिक',
    luckyNumbers: [1, 3, 10],
    luckyDays: ['Sunday', 'Tuesday'],
    luckyDaysNe: ['आइतबार', 'मंगलबार'],
    traits: ['Generous', 'Warm-hearted', 'Creative', 'Enthusiastic'],
    traitsNe: ['उदार', 'न्यानो मन', 'रचनात्मक', 'उत्साही'],
    compatibility: ['Aries', 'Sagittarius', 'Gemini'],
    compatibilityNe: ['मेष', 'धनु', 'मिथुन'],
    direction: 'East',
    directionNe: 'पूर्व',
    metal: 'Gold',
    metalNe: 'सुन',
    flower: 'Sunflower',
    flowerNe: 'सूर्यमुखी'
  },
  virgo: {
    nameEn: 'Virgo',
    nameNe: 'कन्या',
    symbol: '♍',
    element: 'Earth',
    elementNe: 'पृथ्वी',
    gana: 'Manushya',
    ganaNe: 'मनुष्य गण',
    deity: 'Mercury',
    deityNe: 'बुध',
    planet: 'Mercury',
    planetNe: 'बुध',
    luckyColor: 'Green, Brown',
    luckyColorNe: 'हरियो, खैरो',
    gemstone: 'Emerald',
    gemstoneNe: 'पन्ना',
    luckyNumbers: [3, 6, 15],
    luckyDays: ['Wednesday', 'Friday'],
    luckyDaysNe: ['बुधबार', 'शुक्रबार'],
    traits: ['Loyal', 'Analytical', 'Kind', 'Hardworking'],
    traitsNe: ['वफादार', 'विश्लेषणात्मक', 'दयालु', 'मेहनती'],
    compatibility: ['Taurus', 'Capricorn', 'Cancer'],
    compatibilityNe: ['वृषभ', 'मकर', 'कर्कट'],
    direction: 'South',
    directionNe: 'दक्षिण',
    metal: 'Mercury',
    metalNe: 'पारा',
    flower: 'Morning Glory',
    flowerNe: 'बिहानी फूल'
  },
  libra: {
    nameEn: 'Libra',
    nameNe: 'तुला',
    symbol: '♎',
    element: 'Air',
    elementNe: 'वायु',
    gana: 'Rakshasa',
    ganaNe: 'राक्षस गण',
    deity: 'Venus',
    deityNe: 'शुक्र',
    planet: 'Venus',
    planetNe: 'शुक्र',
    luckyColor: 'Blue, Green',
    luckyColorNe: 'नीलो, हरियो',
    gemstone: 'Diamond',
    gemstoneNe: 'हीरा',
    luckyNumbers: [6, 15, 24],
    luckyDays: ['Friday', 'Saturday'],
    luckyDaysNe: ['शुक्रबार', 'शनिबार'],
    traits: ['Cooperative', 'Diplomatic', 'Gracious', 'Fair-minded'],
    traitsNe: ['सहयोगी', 'कूटनीतिक', 'दयालु', 'निष्पक्ष'],
    compatibility: ['Gemini', 'Aquarius', 'Leo'],
    compatibilityNe: ['मिथुन', 'कुम्भ', 'सिंह'],
    direction: 'West',
    directionNe: 'पश्चिम',
    metal: 'Copper',
    metalNe: 'तामा',
    flower: 'Rose',
    flowerNe: 'गुलाब'
  },
  scorpio: {
    nameEn: 'Scorpio',
    nameNe: 'वृश्चिक',
    symbol: '♏',
    element: 'Water',
    elementNe: 'जल',
    gana: 'Rakshasa',
    ganaNe: 'राक्षस गण',
    deity: 'Mars',
    deityNe: 'मंगल',
    planet: 'Mars',
    planetNe: 'मंगल',
    luckyColor: 'Deep Red, Maroon',
    luckyColorNe: 'गाढा रातो, मरुन',
    gemstone: 'Red Coral',
    gemstoneNe: 'मूंगा',
    luckyNumbers: [4, 13, 22],
    luckyDays: ['Tuesday', 'Thursday'],
    luckyDaysNe: ['मंगलबार', 'बिहीबार'],
    traits: ['Resourceful', 'Brave', 'Passionate', 'Stubborn'],
    traitsNe: ['संसाधनशील', 'बहादुर', 'भावुक', 'जिद्दी'],
    compatibility: ['Cancer', 'Pisces', 'Virgo'],
    compatibilityNe: ['कर्कट', 'मीन', 'कन्या'],
    direction: 'North',
    directionNe: 'उत्तर',
    metal: 'Iron',
    metalNe: 'फलाम',
    flower: 'Geranium',
    flowerNe: 'गेरेनियम'
  },
  sagittarius: {
    nameEn: 'Sagittarius',
    nameNe: 'धनु',
    symbol: '♐',
    element: 'Fire',
    elementNe: 'अग्नि',
    gana: 'Deva',
    ganaNe: 'देव गण',
    deity: 'Jupiter',
    deityNe: 'बृहस्पति',
    planet: 'Jupiter',
    planetNe: 'बृहस्पति',
    luckyColor: 'Yellow, Orange',
    luckyColorNe: 'पहेंलो, सुन्तला',
    gemstone: 'Yellow Sapphire',
    gemstoneNe: 'पुखराज',
    luckyNumbers: [3, 9, 21],
    luckyDays: ['Thursday', 'Friday'],
    luckyDaysNe: ['बिहीबार', 'शुक्रबार'],
    traits: ['Generous', 'Idealistic', 'Great sense of humor'],
    traitsNe: ['उदार', 'आदर्शवादी', 'हास्य प्रिय'],
    compatibility: ['Aries', 'Leo', 'Libra'],
    compatibilityNe: ['मेष', 'सिंह', 'तुला'],
    direction: 'Northeast',
    directionNe: 'उत्तर-पूर्व',
    metal: 'Tin',
    metalNe: 'टिन',
    flower: 'Carnation',
    flowerNe: 'कार्नेशन'
  },
  capricorn: {
    nameEn: 'Capricorn',
    nameNe: 'मकर',
    symbol: '♑',
    element: 'Earth',
    elementNe: 'पृथ्वी',
    gana: 'Rakshasa',
    ganaNe: 'राक्षस गण',
    deity: 'Saturn',
    deityNe: 'शनि',
    planet: 'Saturn',
    planetNe: 'शनि',
    luckyColor: 'Black, Dark Blue',
    luckyColorNe: 'कालो, गाढा नीलो',
    gemstone: 'Blue Sapphire',
    gemstoneNe: 'नीलम',
    luckyNumbers: [6, 8, 26],
    luckyDays: ['Saturday', 'Tuesday'],
    luckyDaysNe: ['शनिबार', 'मंगलबार'],
    traits: ['Responsible', 'Disciplined', 'Self-control', 'Good managers'],
    traitsNe: ['जिम्मेवार', 'अनुशासित', 'आत्म-नियन्त्रण', 'राम्रो प्रबन्धक'],
    compatibility: ['Taurus', 'Virgo', 'Scorpio'],
    compatibilityNe: ['वृषभ', 'कन्या', 'वृश्चिक'],
    direction: 'Southwest',
    directionNe: 'दक्षिण-पश्चिम',
    metal: 'Lead',
    metalNe: 'सिसा',
    flower: 'Pansy',
    flowerNe: 'प्यान्सी'
  },
  aquarius: {
    nameEn: 'Aquarius',
    nameNe: 'कुम्भ',
    symbol: '♒',
    element: 'Air',
    elementNe: 'वायु',
    gana: 'Manushya',
    ganaNe: 'मनुष्य गण',
    deity: 'Saturn',
    deityNe: 'शनि',
    planet: 'Saturn',
    planetNe: 'शनि',
    luckyColor: 'Blue, Silver',
    luckyColorNe: 'नीलो, चाँदी',
    gemstone: 'Blue Sapphire',
    gemstoneNe: 'नीलम',
    luckyNumbers: [4, 7, 11],
    luckyDays: ['Saturday', 'Sunday'],
    luckyDaysNe: ['शनिबार', 'आइतबार'],
    traits: ['Progressive', 'Original', 'Independent', 'Humanitarian'],
    traitsNe: ['प्रगतिशील', 'मौलिक', 'स्वतन्त्र', 'मानवतावादी'],
    compatibility: ['Gemini', 'Libra', 'Sagittarius'],
    compatibilityNe: ['मिथुन', 'तुला', 'धनु'],
    direction: 'Southwest',
    directionNe: 'दक्षिण-पश्चिम',
    metal: 'Aluminum',
    metalNe: 'एल्युमिनियम',
    flower: 'Orchid',
    flowerNe: 'अर्किड'
  },
  pisces: {
    nameEn: 'Pisces',
    nameNe: 'मीन',
    symbol: '♓',
    element: 'Water',
    elementNe: 'जल',
    gana: 'Deva',
    ganaNe: 'देव गण',
    deity: 'Jupiter',
    deityNe: 'बृहस्पति',
    planet: 'Jupiter',
    planetNe: 'बृहस्पति',
    luckyColor: 'Sea Green, Aqua',
    luckyColorNe: 'समुद्री हरियो, आक्वा',
    gemstone: 'Yellow Sapphire',
    gemstoneNe: 'पुखराज',
    luckyNumbers: [3, 9, 12],
    luckyDays: ['Thursday', 'Tuesday'],
    luckyDaysNe: ['बिहीबार', 'मंगलबार'],
    traits: ['Compassionate', 'Artistic', 'Intuitive', 'Gentle'],
    traitsNe: ['दयालु', 'कलात्मक', 'अन्तर्ज्ञानी', 'कोमल'],
    compatibility: ['Cancer', 'Scorpio', 'Capricorn'],
    compatibilityNe: ['कर्कट', 'वृश्चिक', 'मकर'],
    direction: 'North',
    directionNe: 'उत्तर',
    metal: 'Tin',
    metalNe: 'टिन',
    flower: 'Water Lily',
    flowerNe: 'जल कमल'
  }
};

export const ZODIAC_LIST = Object.keys(ZODIAC_DATA);